title:            'Mick Chanwut Kittivorawong'
tagline:          'An improved Hyde Jekyll theme.'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              chanwutk.github.io
baseurl:          /

# Build settings
markdown:         kramdown
highlighter:      pygments
permalink:        pretty
paginate:         5

author:
  name:           'Chanwut Kittivorawong'
  email:          chanwutk@gmail.com
  url:            https://emmanuelcorrales.com

social:
  twitter:        chanwutk
  linkedin:       chanwut-k
  github:         chanwutk

google_analytics:
