# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy on Berkeley Domain

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "deploy-berkeley"
  cancel-in-progress: true

jobs:
  # Build and Deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Pages
      #   uses: actions/configure-pages@v2
      - name: Add Base URL
        run: |
          echo 'baseurl: "~chanwutk"' >> _config.yml
      
      - name: Download fonts
        run: |
          wget -O academicons-1.9.4.zip "https://codeload.github.com/jpswalsh/academicons/zip/refs/tags/v1.9.4"
          wget "https://use.fontawesome.com/releases/v6.5.2/fontawesome-free-6.5.2-web.zip"

          unzip academicons-1.9.4.zip
          unzip fontawesome-free-6.5.2-web.zip

          mkdir -p ./assets/webfonts
          cp ./fontawesome-free-6.5.2-web/webfonts/fa-solid* ./assets/webfonts
          cp ./fontawesome-free-6.5.2-web/webfonts/fa-brands* ./assets/webfonts
          cp ./fontawesome-free-6.5.2-web/css/fontawesome.min.css ./assets/css
          cp ./fontawesome-free-6.5.2-web/css/brands.min.css ./assets/css
          cp ./fontawesome-free-6.5.2-web/css/solid.min.css ./assets/css
          rm -rf ./fontawesome-free-6.5.2-web
          rm -rf ./fontawesome-free-6.5.2-web.zip

          mkdir -p ./assets/fonts
          cp ./academicons-1.9.4/fonts/academicons.* ./assets/fonts
          cp ./academicons-1.9.4/css/academicons.min.css ./assets/css
          rm -rf ./academicons-1.9.4
          rm -rf ./academicons-1.9.4.zip

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Minimize CSS
        run: |
          ls -lah ./_site/assets/css
          sudo chmod 666 ./_site/assets/css/*
          npm install -g purgecss
          purgecss                          \
            --css      ./_site/assets/css/* \
            --content  ./_site/**/*.html    \
            --output   ./_site/assets/css   \
            --safelist title-slide-right title-slide-left title-stay-right title-stay-left title-slide-out title-slide-in
          ls -lah ./_site/assets/css
          sudo chmod 644 ./_site/assets/css/*

      - name: Publish Website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: '_site'
          single-commit: true
          branch: berkeley

#       - name: Setup SSH
#         run: |
#           echo "${{secrets.SSH_SECRET_KEY}}" >> id_rsa
#           chmod 600 id_rsa

#       - name: Deploy to Berkeley Domain
#         run: |
#           ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{secrets.BERKELEY_USER}}@${{secrets.BERKELEY_HOST}} "rm -r ~/public_html"
#           scp -o StrictHostKeyChecking=no -i ./id_rsa -r ./_site ${{secrets.BERKELEY_USER}}@${{secrets.BERKELEY_HOST}}:./public_html

#       - name: Clean Up SSH Key
#         run: rm id_rsa
